### ISSUE TITLE
make nest and partition/party_df play nice

### ISSUE THREAD

**Issue by stanstrup** [hadley/multidplyr#24] opened 2016-02-03 01:16 UTC
Ref: https://twitter.com/hadleywickham/status/694687708799578112

Nest fails when encountering a party_df:

``` R
library(gapminder)
library(dplyr)
library(multidplyr)
library(tidyr)

cluster <- create_cluster(4) %>% cluster_library("purrr")

by_country <- gapminder %>% 
              partition(cluster = cluster, continent, country) %>%
              nest() %>% 
              mutate( model = map(data, ~ lm(lifeExp ~ year, data = . ))  ) %>%
              collect()
```

Current workaround:

``` R
library(gapminder)
library(dplyr)
library(multidplyr)
library(tidyr)

cluster <- create_cluster(4) %>% cluster_library("purrr")

by_country <- gapminder %>% 
              group_by(continent, country) %>% 
              nest() %>% 
              partition(cluster = cluster, continent, country) %>% 
              mutate( model = map(data, ~ lm(lifeExp ~ year, data = . ))  ) %>%
              collect()
```

**Comment by kendonB** [comment] 2016-06-20 20:10
Could also add automatic exporting of user defined functions for ``map()``. Will need to be careful not to let ``clusterExport`` send the entire enclosing environment as it usually does when sending functions

**Comment by hadley** [comment] 2019-06-27 22:46
Duplicate of #67

**Closed by hadley** 2019-06-27 22:46 UTC
