### ISSUE TITLE
Partition not working

### ISSUE THREAD

**Issue by fugufisch** [hadley/multidplyr#6] opened 2015-11-12 08:59 UTC
I am having an issue with partioning a dataframe, which I don't understand. The grouped df looks as follows:

```
p2012 %>% group_by(year, month)
Source: local data frame [6,171,602 x 17]
Groups: year, month [6]

      ID  year   month            datetime        x       y sensor.depth dist_from_shore datapoint.number metadata.date       PIT length.total
   (int) (dbl)  (fctr)              (time)    (dbl)   (dbl)        (dbl)           (int)            (int)         (int)    (fctr)        (int)
1  41500  2011 October 2011-10-28 16:09:35 404703.4 5872714        3.519             132                9             1 116606026          504
2  41500  2011 October 2011-10-18 14:50:09 404722.3 5872716           NA             115                1             1 116606026          504
3  41500  2011 October 2011-10-27 12:11:07 404700.2 5872720        3.312             131                2             1 116606026          504
4  41500  2011 October 2011-10-28 08:19:37 404704.2 5872712           NA             131                3             1 116606026          504
5  41500  2011 October 2011-10-28 11:58:46 404703.8 5872712        3.312             132                4             1 116606026          504
6  41500  2011 October 2011-10-31 00:48:36 404712.1 5872728           NA             116               31             1 116606026          504
7  41500  2011 October 2011-10-31 00:51:08 404712.1 5872728        3.726             116               32             1 116606026          504
8  41500  2011 October 2011-10-31 00:51:33 404712.1 5872728        3.726             116               33             1 116606026          504
9  41500  2011 October 2011-10-31 00:56:08 404712.1 5872728        3.726             116               34             1 116606026          504
10 41500  2011 October 2011-10-31 01:04:26 404712.0 5872728           NA             116               35             1 116606026          504
..   ...   ...     ...                 ...      ...     ...          ...             ...              ...           ...       ...          ...
```

Grouping works fine, but partitioning throws the following error:

```
> p2012 %>% 
+   partition(year, month)

Error: length(values) == length(cluster) is not TRUE
```

I have a 32 core machine and `multidplyr` tries to allocate 31 cores. Creating a different cluster with fewer nodes does also produce the same error most of the time. The strange part is that it sometimes seems to work in a random fashion.

**Comment by hadley** [comment] 2015-11-12 12:45
Without a reproducible example, I think you'll need to step through the code in `partition()` yourself, and figure out what's going wrong.

How many total combinations of year and month do you have? It's possible that it's small and because of the randomisation partition does, sometimes there aren't enough to spread over 31 nodes?

**Comment by fugufisch** [comment] 2015-11-12 13:11
Yes, it's only 6 combinations. But even if I initialize a cluster with only 5 or 6 nodes I get this error. 
It works if I only use 2 nodes though.

I get the same error with:
```
data(movies)
movies %>% partition(length)
```
This works:
```
movies %>% partition(length, cluster=create_cluster(2))
```
So I always need more combinations than nodes? How do I know how many nodes I can use?

**Comment by hadley** [comment] 2015-11-12 13:34
You shouldn't _have_ to but clearly there's a bug in my implementation of `partition()`.

**Comment by fugufisch** [comment] 2015-11-12 15:30
Ok, I'll see if I can fix it and maybe make a pull request. Thanks!

**Comment by jmorten** [comment] 2015-12-10 01:24
I am having the same problem. I have 35,000,000 lines with 4,600,000 unique values that I am partitioning on. I would assume that partition would be able to create shards given the input. 

I tried with 32 partitions, 16, 8, 7, all failed. However, as above, 2 partitions do work.

**Comment by fugufisch** [comment] 2015-12-10 08:27
I did a fix for this in my fork that solved the issue for me. It would be great if you could test my fix with your dataset.

**Comment by jmorten** [comment] 2015-12-13 05:32
I would love to implement your fix, but I believe there might be an underlying issue since `partition()` works in a random manor.

I will restart my session and `partition()` will work, while other times it does not.

**Comment by gdbassett** [comment] 2016-01-24 21:22
I also get the "Error: length(values) == length(cluster) is not TRUE" error when placing a feature in "partition".  It even happens when a cluster is created the same length as unique features on the partitioned features.
```
> names(bla)
 [1] "id"        "sha256"    "timestamp" "src_port"  "dst_port"  "thing"       "thing2"  "thing3"     "thing4"       "thing5"
> length(unique(bla$thing4))
[1] 20
> cluster <- create_cluster(20)
Initialising 20 core cluster.
> chunk <- bla %>% partition(thing4, cluster=cluster) %>% group_by(thing3, thing4) %>% summarize(x=n()) %>% collect() %>% group_by(thing2) %>% mutate(n=sum(x), freq=x/n) %>% select(industry, ext, x, n, freq) %>% ungroup()
Error: length(values) == length(cluster) is not TRUE
```
I get the same error if 'cluster' isn't specified in partition or if the cluster size is 10 or 5 cores.

**Comment by julou** [comment] 2016-04-12 16:37
a fix for this would be really helpful.
For now I'm leaving with the workaround of @fugufisch i.e. using my cluster[1:n] where n is smaller than the number of shards…

btw, I would say that https://github.com/fugufisch/multidplyr/commit/fee752ee29419eb1c4a9783174cd5a0b76a0e25e is more general than https://github.com/Ax3man/multidplyr/commit/cd04680a03d76712055d4db56520a13555a569c6 which as far as I understand is only relevant when no cluster argument is passed (but maybe I missed some subtlety…)

**Comment by Ax3man** [comment] 2016-04-12 19:54
IIRC @fugufisch didn't always work for me (depending on the random shard distribution I think).

I think you're right on the use of my fork. I sometimes pass a specific cluster to `partition` where other things may already be on, for example for joining different things together. I then rely that my data actually is loaded on that partition. If `partition` instead silently creates a new cluster and puts my data on there, I'm going to be confused and a little annoyed. That's why I chose to let a mismatch between the size of a specified cluster and the number of groups to still return an error.

**Comment by julou** [comment] 2016-04-12 20:07
@Ax3man could you elaborate?
this fix is only subsetting the cluster in case there are less shards than nodes…

**Comment by Ax3man** [comment] 2016-04-12 20:10
Hmm, sorry that was another bug that I fixed that day. I now see they were separate commits. But it does create an oversized cluster (when cluster isn't specified).

**Comment by sw1sh** [comment] 2016-06-16 07:32
I have the same problem with partitioning data.frame that is also belongs to 'data.table' class (because I use fread for fast reading). So the solution in this case is simply `class(df) <- 'data.frame'`.

**Comment by gmonaie** [comment] 2016-08-11 19:10
The line creating the issue is in `partition_` where groups are being assigned to partitions or shards.

shard.R#51
`groups$part_id <- floor(m * (cumsum(groups$n) - 1) / sum(groups$n) + 1)`

As an example, number of rows (n) is 18, number of shards (m) is 5.

data is to be partitioned by date, looks like this:

```
> data %>% select(date)
Source: local data frame [18 x 1]
Groups: date

         date
1  2016-08-04
2  2016-08-04
3  2016-08-10
4  2016-08-10
5  2016-08-10
6  2016-08-10
7  2016-08-11
8  2016-08-11
9  2016-08-11
10 2016-08-11
11 2016-08-11
12 2016-08-11
13 2016-08-11
14 2016-08-11
15 2016-08-17
16 2016-08-17
17 2016-08-18
18 2016-08-18
```

Before assigning partitions:

```
> groups
Source: local data frame [5 x 2]

  id n
1  4 2
2  3 8
3  1 2
4  5 2
5  2 4
```

shard.R#51 `groups$part_id <- floor(m * (cumsum(groups$n) - 1) / sum(groups$n) + 1)`
This part_id assignment makes an uneven assignment of groups to shards with this result:

```
> groups
Source: local data frame [5 x 3]

  id n part_id
1  4 2       1
2  3 8       3
3  1 2       4
4  5 2       4
5  2 4       5
```

We can either change line #51 or change the cluster assignment to have a 1 to 1 mapping with the shards on line #59

`cluster_assign_each(cluster[as.integer(names(shards))], name, shards)`

**Comment by kendonB** [comment] 2016-08-15 22:31
Please see and test my solution at https://github.com/kendonB/multidplyr

**Comment by cwbishop** [comment] 2017-01-04 21:57
Running into this frequently as well when the number of unique groups < the number of cores in cluster.

Minimal reproducible example below

```
# Example data
library(nycflights13)

# Fails
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(2) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)

# Fails
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(1) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)

# Works
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(1:2) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)
```

I have not had a chance to try the fix suggested by @kendonB.

**Comment by cwbishop** [comment] 2017-01-04 22:06
I'm a huge fan of this package, but I am also running into the same issue frequently when the number of partitions < the number of cores in the cluster.

My typical work flow is to create a forked cluster across all available cores after loading all necessary libraries, etc. in my interactive environment. I then leverage this cluster as needed for embarrassingly parallel operations (e.g., repetitive queries against a database, partition-wise computations or summaries, etc.). Cluster creation in this case is a heavy operation and thus creating a new cluster for each computation is prohibitively time consuming. It is also difficult to preemptively detect edge cases in which I have fewer partitions than cores in my cluster. The result is frequent errors and crashes.

Minimal reproducible example below.

```
# Example data
library(nycflights13)

# Fails
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(1) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)

# Fails
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(2) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)

# Works
flights %>% group_by(dest) %>% slice(1) %>% ungroup() %>% slice(1:2) %>% multidplyr::partition(dest, cluster=multidplyr::create_cluster(2)) %>% mutate(new_col=arr_time - 10) %>% collect(n=Inf)
```

I have not yet had a chance to try the solution suggested by @kendonB, but wanted to provide add a reproducible example.

**Closed** 2017-01-25 23:21 UTC
