### ISSUE TITLE
group_by keeps old groups.

### ISSUE THREAD

**Issue by Ax3man** [hadley/multidplyr#28] opened 2016-03-29 09:33 UTC
When defining new groups, in 'regular' `dplyr` the grouping is overwritten. In `multiplyr`, more and more groups are stacked on.

``` r
library(nycflights13)
flights1 <- partition(flights, flight)
flights1 <- group_by(flights1, month)
flights1 <- group_by(flights1, day)
flights1 <- group_by(flights1, month)
```

``` r
Source: party_df [336,776 x 16]
Groups: flight, month, day, month
Shards: 7 [47,967--48,341 rows]

    year month   day dep_time dep_delay arr_time arr_delay carrier tailnum flight
   (int) (int) (int)    (int)     (dbl)    (int)     (dbl)   (chr)   (chr)  (int)
1   2013     1     1      557        -3      709       -14      EV  N829AS   5708
2   2013     1     1      558        -2      849        -2      B6  N793JB     49
3   2013     1     1      558        -2      924         7      UA  N29129    194
4   2013     1     1      558        -2      923       -14      UA  N53441   1124
5   2013     1     1      559         0      702        -4      B6  N708JB   1806
6   2013     1     1      559        -1      854        -8      UA  N76515   1187
7   2013     1     1      623        -4      933         1      UA  N459UA    496
8   2013     1     1      629        -1      824        -9      US  N426US   1019
9   2013     1     1      643        -3      922       -18      UA  N497UA    556
10  2013     1     1      653        -7      936       -33      DL  N327NW   1383
..   ...   ...   ...      ...       ...      ...       ...     ...     ...    ...
Variables not shown: origin (chr), dest (chr), air_time (dbl), distance (dbl), hour
  (dbl), minute (dbl)
```

**Comment by wosiu** [comment] 2016-04-04 19:51
To my mind this multiplyr's behaviour is better one.
However I find one more group_by connected thing which doesn't work intuitively - I'm going to describe it in anouther issue.

**Comment by jpmorris** [comment] 2016-04-04 20:47
I'm having this same problem dplyr has 'ungroup'  but we can't use this with party_df. So there really is no solution to deal with multiple groupings, i.e.,

`out <- in %>%
   partition(first, cluster=cluster) %>%
   group_by(first) %>%
   mutate(one = n())
   group_by(first, second) %>%
   mutate(two = n())`

one and two will always have be the same.

**Comment by picarus** [comment] 2018-04-27 22:40
The problem is a bit worst, even after collect, the old groups remain but the totals provided by ip, correspond to the table totals (what makes a workaround easy but requires fixing).

```
tr <- partition(train, ip, cluster=cluster) # that will group by ip
tb <- tr %>% 
  group_by(ip, is_attributed) %>% # ip because will be there anyway, make it explicit
  summarise(n=n()) %>% 
  collect() %>% 
  ungroup() %>% 
  group_by(is_attributed, add=F) %>% 
  mutate(n=sum(n)) %>%    
  mutate(pct=n/nr) %>% 
  head(10)
tb
```


ip | is_attributed | n | pct |  
-- | -- | -- | -- | --
31 | 0 | 184447044 | 9.81598937 |  
31 | 1 | 456846 | 0.02431264 |  
231 | 0 | 184447044 | 9.81598937 |  
231 | 1 | 456846 | 0.02431264 |  
279 | 0 | 184447044 | 9.81598937 |  
279 | 1 | 456846 | 0.02431264 |  
372 | 0 | 184447044 | 9.81598937 |  
372 | 1 | 456846 | 0.02431264 |  
433 | 0 | 184447044 | 9.81598937 |  
433 | 1 | 456846 | 0.02431264

**Comment by hadley** [comment] 2019-07-12 07:29
Now fixed in dev

**Closed by hadley** 2019-07-12 07:29 UTC
Labels: bug
